env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2016
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1 
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  no-console: 'off'
  no-unused-vars: 'off'
