kind: Secret
apiVersion: v1
metadata:
  name: registry2-master
type: Opaque
data:
  REGISTRY2_SECRETKEY: ""
  REGISTRY2_S3_KEY: ""
  REGISTRY2_S3_SECRET: ""
  API_TOKENAUTH_CRT: "" 
  LOGENTRIES_TOKEN: ""
