kind: Service
apiVersion: v1
metadata:
  name: registry2
spec:
  selector:
    component: registry2
  ports:
    -
      name: defaultport
      protocol: TCP
      port: 80
      targetPort: defaultport
