version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Start Kubernetes
          command: |
            docker run -d --name kube --privileged -p 8443:8443 -p 10080:10080 bsycorp/kind:latest-1.12
      - run:
          name: Build Test Stack
          command: |
            docker-compose -f test/docker-compose.test.yml build
      - run:
          name: Wait for Kubernetes
          command: |
            until curl -s --fail http://127.0.0.1:10080/kubernetes-ready; do
              sleep 1;
            done
            echo "Ready - start tests!"
      - run:
          name: Start Test Stack
          command: |
            export KATAPULT_KUBE_CONFIG="$(curl --silent http://localhost:10080/config 2>&1)"
            docker-compose -f test/docker-compose.test.yml up -d
      - run:
          name: Run Tests
          command: |
            docker-compose -f test/docker-compose.test.yml exec tests npm run test

