# Defines supported kompose labels.
# This configuration is required, because we need to use explicit labels in deploy spec template.

supported-environment-template-labels:
  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'labels.aws-load-balancer-ssl-cert'
  kompose.image-pull-secret: 'labels.image-pull-secret'
